spring:
  application:
    name:
      Miroku-API
  # 数据源
  datasource:
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/miroku_api
    # 数据库用户名 从环境变量导入
    username: ${MYSQL_USERNAME:}
    # 数据库密码 从环境变量导入
    password: ${MYSQL_PASSWORD:}
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis 配置
mybatis:
  # Mapper XML 文件路径
  mapper-locations: classpath:mapper/*.xml
  # 实体类包路径（XML 里可省略全限定名）
  type-aliases-package: cn.net.miroku.dto
  configuration:
    # 自动下划线转驼峰
    map-underscore-to-camel-case: true
    # 打印完整 SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: -1
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 前缀
  token-prefix: Bearer
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  # is-concurrent: false
  # 最大登录数
  # max-login-count: 1


# 多模型配置
models:
  # deepseek 配置
  deepseek:
    base-url: https://api.deepseek.com/v1
    api-key: ${DEEPSEEK_API_KEY:}
  # 豆包 配置
  doubao:
    base-url: https://ark.cn-beijing.volces.com/api/v3
    api-key: ${DOUBAO_API_KEY:}
  qwen:
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
    api-key: ${QWEN_API_KEY:}

  # 可用的模型列表
  model-data-list:
    - id: deepseek-chat
      owned_by: deepseek
    - id: deepseek-reasoner
      owned_by: deepseek
    - id: doubao-seed-2-0-mini-260215
      owned_by: 火山引擎
    - id: doubao-seed-2-0-pro-260215
      owned_by: 火山引擎
    - id: doubao-1-5-pro-32k-250115
      owned_by: 火山引擎
    - id: qwen3.6-flash
      owned_by: 阿里云
    - id: qwen3.6-plus
      owned-by: 阿里云
